name: Auto Version Bump

on:
  push:
    branches:
      - main
      - development

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Version Name
        shell: bash
        run: |
          VERSION_MAJOR=$(grep VERSION_MAJOR gradle.properties | cut -d'=' -f2 | xargs)
          VERSION_MINOR=$(grep VERSION_MINOR gradle.properties | cut -d'=' -f2 | xargs)
          RUN_NUMBER=${{ github.run_number }}

          APK_VERSION=${VERSION_MAJOR}.${VERSION_MINOR}.${RUN_NUMBER}

          echo "APK_VERSION=$APK_VERSION" >> $GITHUB_ENV

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ env.APK_VERSION }}
